In [4]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

import pandas as pd
import numpy as np

# 유저 평점 + 영화 속성 데이터 경로 정의
MOVIE_DATA_PATH = 'dataset/movie_rating.csv'

# pandas로 데이터 불러 오기
movie_rating_df = pd.read_csv(MOVIE_DATA_PATH)

features =['romance', 'action', 'comedy', 'heart-warming'] # 사용할 속성들 이름

movie_rating_df

     romance    action    comedy  heart-warming  rating
0   0.740458  0.733800  0.526879       0.332906     3.0
1   0.658391  0.825211  0.608177       0.906809     5.0
2   0.680250  0.401992  0.400964       0.535223     2.0
3   0.572216  0.312618  0.496313       0.319996     1.0
4   0.543545  0.623021  0.713110       0.696774     4.0
..       ...       ...       ...            ...     ...
95  0.431629  0.803459  0.330847       0.423794     3.0
96  0.829724  0.657431  0.493758       0.432268     3.0
97  0.685688  0.760196  0.661252       0.534698     4.0
98  0.643441  0.848488  0.677173       0.638528     5.0
99  0.374184  0.517988  0.733646       0.546950     3.0

[100 rows x 5 columns]

In [5]:
# 입력 변수와 목표 변수 나누기
X = movie_rating_df[features]
y = movie_rating_df[['rating']]

# 입력 변수와 목표 변수들을 각각의 training/test 셋으로 나누기
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=5)


model = LinearRegression()
model.fit(X_train, y_train)

y_test_predict = model.predict(X_test)
# 실행 코드
y_test_predict

array([[3.83034441],
       [2.59418977],
       [2.63653566],
       [3.48333221],
       [2.75217812],
       [2.43303141],
       [3.03247628],
       [4.41312853],
       [4.28145539],
       [3.61139607],
       [3.82260281],
       [3.01099122],
       [3.06324646],
       [4.41401949],
       [4.08837667],
       [3.30347874],
       [4.69514621],
       [4.3397661 ],
       [3.42084949],
       [3.94638571]])